# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergoview" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "340ece5751890f3cbff6e3ac03a796fff8a217abb17dc0845e1caa15e59b225a"
      url "https://github.com/jamestjsp/ergoview/releases/download/v#{version}/ergoview_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1284860d9fb121298e8a5ceb0fd72c0cf4376d58dca45f2d5aae889abcdee18e"
      url "https://github.com/jamestjsp/ergoview/releases/download/v#{version}/ergoview_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d378bd20c0d3a21ef49c8aacce1b8a729f4530c894ac2d55392ab17cd6f63dff"
      url "https://github.com/jamestjsp/ergoview/releases/download/v#{version}/ergoview_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcf8d6569cfb896e0ac6a102301118b0f2e2ac0a6d6fb5428e96a5199a997069"
      url "https://github.com/jamestjsp/ergoview/releases/download/v#{version}/ergoview_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ergoview"
  desc "Terminal companion for Ergo task graphs"
  homepage "https://github.com/jamestjsp/ergoview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ev"]
    end
  end

  # No zap stanza required

end
