# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergoview" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "1411e4348b72b7c869903735b94f548deb4043aa67f1068eb6db558be7fa1721"
      url "https://github.com/jamestjsp/ergoview/releases/download/v#{version}/ergoview_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "04f3ec00b074fa61159d70366a4d151517d308020467b31019a3bfe5975597a3"
      url "https://github.com/jamestjsp/ergoview/releases/download/v#{version}/ergoview_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ffc7f8334d204090206c28916918d2b0680ee387838c70186de5be8f07400a52"
      url "https://github.com/jamestjsp/ergoview/releases/download/v#{version}/ergoview_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "697c60cd648f5fdbf1d1b53c445887a0a5b38a4e1daa3109a257ef5f50ce8857"
      url "https://github.com/jamestjsp/ergoview/releases/download/v#{version}/ergoview_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ergoview"
  desc "Terminal companion for Ergo task graphs"
  homepage "https://github.com/jamestjsp/ergoview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ev"]
    end
  end

  # No zap stanza required

end
